service:
    name: ts-serverless-project
    # app and org for use with dashboard.serverless.com
    #app: your-app-name
    #org: your-org-name
    stage: dev
    # region: region
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    apiGateway:
        minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    environment:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

include:
    - ./src/**
exclude:
    - node_modules/**
functions:
    app:
        handler: ./src/app.hello
        events:
            - http:
                  method: get
                  path: hello
